name: pattern_box
description: "A collection of patterned background in Flutter using Custom Painter"
repository: https://github.com/thisisprabhat/pattern_box.git
homepage: https://github.com/thisisprabhat/pattern_box.git

version: 0.5.3

topics:
- canvas
- background
- painter
- pattern
- decoration

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# screenshots:
#   - description: The pattern_box package logo.
#     path: example/images/pattern_box_logo.png



environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  
  # assets:
  #   - assets/patterns/


license: MIT